version: "3"

services:
  monitoring-service:
    build:
      context: .
    ports:
      - 8080:8080
    environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/applifting
    depends_on:
      - mysql-db
  mysql-db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=pwd
      - MYSQL_PASSWORD=pwd
      - MYSQL_DATABASE=applifting
    restart: unless-stopped